-- MySQL Script generated by MySQL Workbench
-- Sun Aug  5 13:09:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_product
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_product
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_product` DEFAULT CHARACTER SET utf8 ;
USE `db_product` ;

-- -----------------------------------------------------
-- Table `db_product`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`sale` ;

CREATE TABLE IF NOT EXISTS `db_product`.`sale` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` VARCHAR(45) NOT NULL,
  `product_barcode` VARCHAR(45) NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `count` DOUBLE NOT NULL,
  `price` DOUBLE NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `seller_id` VARCHAR(45) NOT NULL,
  `seller_name` VARCHAR(45) NOT NULL,
  `customer_id` VARCHAR(45) NOT NULL,
  `customer_name` VARCHAR(45) NOT NULL,
  `sale_date` VARCHAR(255) NOT NULL,
  `time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `paymentType` VARCHAR(45) NULL DEFAULT NULL,
  `valyuta` VARCHAR(45) NULL DEFAULT NULL,
  `Number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_product`.`sale_no`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`sale_no` ;

CREATE TABLE IF NOT EXISTS `db_product`.`sale_no` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Seller_id` VARCHAR(45) NOT NULL,
  `Customer_id` VARCHAR(45) NOT NULL,
  `Date` DATETIME NOT NULL,
  `sum` REAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_product`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`customer` ;

CREATE TABLE IF NOT EXISTS `db_product`.`customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_product`.`muhasibat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`muhasibat` ;

CREATE TABLE IF NOT EXISTS `db_product`.`muhasibat` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `qaime_nomresi` VARCHAR(45) NOT NULL,
  `qaime_novu` VARCHAR(45) NOT NULL,
  `alinan_sirketin_adi` VARCHAR(45) NOT NULL,
  `mehsullarin_siyahisi` VARCHAR(45) NOT NULL,
  `qeyd` MEDIUMTEXT NULL DEFAULT NULL,
  `qaime_zamani` DATE NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_product`.`product_changed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`product_changed` ;

CREATE TABLE IF NOT EXISTS `db_product`.`product_changed` (
  `id` INT(10) NOT NULL,
  `product_id` INT NOT NULL,
  `barcode` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `commission` VARCHAR(45) NOT NULL,
  `price_new` VARCHAR(45) NOT NULL,
  `price_last` VARCHAR(45) NOT NULL,
  `last_refused_product_count` VARCHAR(45) NULL,
  `last_count` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_product`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`products` ;

CREATE TABLE IF NOT EXISTS `db_product`.`products` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `product_code` VARCHAR(45) NULL DEFAULT NULL,
  `barcode` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(45) NULL DEFAULT NULL,
  `saled_count` DOUBLE NOT NULL DEFAULT '0',
  `unit` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL DEFAULT '0',
  `lastpriceChange` VARCHAR(45) NULL DEFAULT NULL,
  `currency` VARCHAR(45) NOT NULL DEFAULT 'AZN',
  `commission` VARCHAR(45) NOT NULL DEFAULT '0',
  `stock_count` DOUBLE NULL DEFAULT '0',
  `alis_qiymeti` DOUBLE NULL DEFAULT NULL,
  `xetali_mehsul_sayi` DOUBLE NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_products_sale2_idx` (`barcode` ASC),
  INDEX `fk_products_sale3_idx` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_product`.`qaime_mehsul`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`qaime_mehsul` ;

CREATE TABLE IF NOT EXISTS `db_product`.`qaime_mehsul` (
  `id` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `qaime_id` INT(11) NOT NULL,
  `barcode` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `buy_price` VARCHAR(45) NULL DEFAULT NULL,
  `value` VARCHAR(45) NOT NULL,
  `unit` VARCHAR(45) NULL DEFAULT NULL,
  `comission` VARCHAR(45) NULL DEFAULT NULL,
  `sale_price` VARCHAR(45) NULL DEFAULT NULL,
  `currency` VARCHAR(45) NULL DEFAULT NULL,
  `qeyd` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `qaime_id`),
  INDEX `fk_qaime_mehsul_muhasibat1_idx` (`qaime_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_product`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`users` ;

CREATE TABLE IF NOT EXISTS `db_product`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `is_enable` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_product`.`customer_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`customer_info` ;

CREATE TABLE IF NOT EXISTS `db_product`.`customer_info` (
  `customer_id` INT(11) NOT NULL,
  `logo` BLOB NULL,
  `unvan` VARCHAR(255) NULL,
  `e_mail` VARCHAR(65) NULL,
  `fax_number` VARCHAR(45) NULL,
  INDEX `fk_customer_info_customer1_idx` (`customer_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_product`.`users_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`users_info` ;

CREATE TABLE IF NOT EXISTS `db_product`.`users_info` (
  `users_id` INT(10) UNSIGNED NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `phone` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `users_infocol` VARCHAR(45) NOT NULL,
  INDEX `fk_users_info_users1_idx` (`users_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_product`.`users_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`users_status` ;

CREATE TABLE IF NOT EXISTS `db_product`.`users_status` (
  `users_id` INT(10) UNSIGNED NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 0,
  `last_sign_date` VARCHAR(45) NULL,
  INDEX `fk_users_status_users1_idx` (`users_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_product`.`user_photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`user_photo` ;

CREATE TABLE IF NOT EXISTS `db_product`.`user_photo` (
  `users_id` INT(10) UNSIGNED NOT NULL,
  `photo` LONGBLOB NOT NULL,
  PRIMARY KEY (`photo`),
  INDEX `fk_user_photo_users1_idx` (`users_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_product`.`employee_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`employee_permissions` ;

CREATE TABLE IF NOT EXISTS `db_product`.`employee_permissions` (
  `name` VARCHAR(255) NOT NULL,
  `value` INT(1) UNSIGNED NOT NULL,
  `is_enabled` INT(1) UNSIGNED NULL DEFAULT 0,
  `users_id` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_employee_permissions_users1_idx` (`users_id` ASC));


-- -----------------------------------------------------
-- Table `db_product`.`product_update`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_product`.`product_update` ;

CREATE TABLE IF NOT EXISTS `db_product`.`product_update` (
  `product_changed_id` INT(10) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_product_update_product_changed1_idx` (`product_changed_id` ASC));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
